<!-- eslint-disable vue/multi-word-component-names -->
<template>
  <v-card class="m-2">
    <div class="m-4">
      <v-card-title>General Disclosure</v-card-title>
      <p>Strain Investment Company LLC operates a website at michael-strain.com (the “Site”). The information contained on the Site neither constitutes an offer for nor a solicitation of interest in any securities offering; however, if an indication of interest is provided, it may be withdrawn or revoked, without obligation or commitment of any kind prior to being accepted following the qualification or effectiveness of the applicable offering document, and any offer, solicitation or sale of any securities will be made only by means of an offering circular, private placement memorandum, or prospectus and related operating agreement and subscription documents. No money or other consideration is hereby being solicited and will not be accepted without such potential investor having been provided the applicable offering document, and with respect to Regulation A offerings, such offering document being qualified with the SEC and the sale of such securities being permitted by state law. Joining the Site neither constitutes an indication of interest in any offering nor involves any obligation or commitment of any kind.</p>
      <br>
      <p>PAST PERFORMANCE IS NO GUARANTEE OF FUTURE RESULTS, AND ANY EXPECTED RETURNS OR HYPOTHETICAL PROJECTIONS MAY NOT REFLECT ACTUAL FUTURE PERFORMANCE. FURTHERMORE, PAST RETURNS MAY REFLECT THE PERFORMANCE OF ASSETS FOR A FINITE TIME, OR DURING A PERIOD OF EXTREME MARKET ACTIVITY. ALL INVESTMENTS INVOLVE RISK AND MAY RESULT IN PARTIAL OR TOTAL LOSS. There can be no assurance that an investment mix or any projected or actual performance shown on the Site will lead to the expected results shown or perform in any predictable manner. It should not be assumed that investors will experience returns in the future, if any, comparable to those shown or that any or all investors on the Site experienced such returns.</p>
      <br>
      <v-card-title>Historical and Projected Performance Disclosure</v-card-title>
      <p>In considering any performance information shown on the Site, one should bear in mind that past or targeted performance is not indicative of future results, and there can be no assurance that any issuer will achieve comparable results or that target returns will be met. One should also bear in mind that targeted portfolio characteristics are not indicative of future results, and there is no assurance that target portfolio characteristic will be achieved.</p>
      <br>
      <p>References to “Targeted IRR” and “Targeted Cash Flow” represents a property's internal rate of return (“IRR”) or cash flow yield based on such property's forecasted cash flows generated over a period of time and the amount invested in the property. This could be different from the forecasted IRR or forecasted cash flow to the investor in an applicable fund or other investment vehicle.</p>
      <br>
      PROJECTED AND/OR HYPOTHETICAL PERFORMANCE DOES NOT REPRESENT AN ACTUAL INVESTMENT IN ANY OF THE OFFERINGS SPONSORED BY STRAIN INVESTMENT COMPANY LLC, MAY NOT REFLECT THE POTENTIAL EFFECT OF MATERIAL ECONOMIC AND MARKET RELATED FACTORS, AND DO NOT REPRESENT THE ACTUAL PERFORMANCE OR EXPERIENCE OF ANY GIVEN INVESTOR ON THE STRAIN INVESTMENT COMPANY LLC WEBSITE. Nothing contained on the Site should be deemed to be a prediction for projection of future performance of any issuer. Prospective investors should make their own investigations and evaluations of the information contained herein. Each prospective investor should consult its own attorney, business adviser and tax adviser as to legal, business, tax and related matters concerning the information contained herein and such offering.
      <br>
      <p>The information shown on the Site uses or includes information compiled from sources outside of Strain Investment Company LLC and its affiliates. While such information is believed to be reliable for the purposes used herein, neither Strain Investment Company LLC, nor any of its affiliates or partners, members or employees, assume any responsibility for the accuracy of such information. Unless otherwise indicated, the information on the Site has not been reviewed, compiled or audited by any independent third-party or public accountant.</p>
      <br>
      <p>Actual investors on the Site may experience different results from any hypothetical results shown. There is a potential for loss, as well as gain, which is not reflected in the hypothetical information portrayed. The hypothetical performance results shown do not represent the results of actual investment activity but were achieved by means of the retroactive application of a model designed with the benefit of hindsight. Investors should carefully review the additional information presented on the Site as part of any hypothetical calculation.</p>
      <br>
      <v-card-title>Offering Disclosure</v-card-title>
      <p>The offerings available on the Site, except where otherwise indicated (i.e. Regulation A offerings), are only open to independently verified “accredited investors,” in accordance with Rule 506(c) under Regulation D of the Securities Act of 1933, pursuant to each issuer's private placement memorandum, or prospectus. Prior to investing, you will be asked to independently verify your “accredited investor” status, except where otherwise indicated.</p>
      <br>
      <p>For our current Regulation A offering(s), no sale may be made to you in this offering if the aggregate purchase price you pay is more than 10% of the greater of your annual income or net worth (excluding your primary residence, as described in Rule 501(a)(5)(i) of Regulation D). Different rules apply to accredited investors and non-natural persons.  Before making any representation that your investment does not exceed applicable thresholds, we encourage you to review Rule 251(d)(2)(i)(C) of Regulation A.  For general information on investing, we encourage you to refer to www.investor.gov.</p>
      <br>
      <p>Offers to sell, or solicitations of offers to buy, any security can only be made through official offering documents that contain important information about investment objectives, risks, fees and expenses. Investors are encouraged to consult with a financial advisor, attorney, accountant, and any other professional that can help you to understand and assess the risks associated with any investment opportunity.</p>
      <br>
      <p>Some of the statements contained on the Site are forward-looking statements. You should not rely upon forward-looking statements as predictions of future events. These statements involve known and unknown risks, uncertainties, and other factors that may cause the project's actual results, levels of activity, performance, or achievements to be materially and adversely different from any future results, levels of activity, performance, or achievements expressed or implied by these forward-looking statements. An investment in any issuer available on the Site involves substantial risks, including risk of partial or total loss of investment, and each investor should carefully consider the Risk Factors contained in each issuer's offering circular, private placement memorandum, or prospectus. Except as required by law, neither we nor any other person assumes responsibility for the accuracy and completeness of the forward-looking statements. We undertake no obligation to update publicly any forward-looking statements for any reason to conform these statements to actual results or to changes in our expectations.</p>
      <br>
      <p>Properties identified as potential acquisitions are subject to various contingencies and may not be consummated or may be consummated on materially different terms. Even if an identified property is acquired by Strain Investment Company LLC and its affiliates, there is no guarantee that all or any of our Regulation A or Regulation D funds will participate in that investment. Additional information concerning identified properties may be posted at www.michael-strain.com as the acquisition process continues.  The acquisition of properties to be invested in as part of a Regulation A offerings will also be promptly announce in that Company's SEC filings. </p>
      <br>
      <p>The information presented regarding each issuer's offering, including information regarding financial status, business strategy, investment objectives, historical performance, projections, redemption plans, etc., merely constitute a summary of such information and is qualified in its entirety by the disclosure contained in each issuer's offering circular, private placement memorandum, or prospectus. There can be no guarantee that any issuer available on the Site will achieve its business objectives or that it will become profitable.</p>
      <br>
      <p>Securities sold by Strain Investment Company LLC are not publicly traded and, therefore, are illiquid unless registered with the SEC. Additionally, securities sold though private placements may be subject to restrictions on resale or transfer including holding period requirements. Investing in private placements requires high risk tolerance, low liquidity need, and long-term commitments. Users must be able to afford to lose their entire investment.</p>
      <br>
      <p>All information contained in the Site has been prepared without reference to any particular investor's investment requirements or financial situation. The Site may not be used by any person or entity in any jurisdiction where the use thereof would be contrary to applicable laws, rules or regulations of any governmental authority, regulatory or self-regulatory organization or clearing organization.</p>
      <br>
      <p>Neither the SEC nor any state securities commission or regulatory authority approved, passed upon or endorsed the merits of any investment on the Site.</p>
      <br>
      <v-card-title>Reviews and Comments Disclosure</v-card-title>
      <br>
      <p>All ratings and reviews are provided to various independent social media sites voluntarily. The average rating review is determined by the various independent social media sites, and not by Strain Investment Company LLC or any of its affiliates. Ratings and reviews are added continuously to the independent social media sites and average ratings are updated by the independent social media websites and not by Strain Investment Company LLC.</p>
      <br>
      <p>The ratings and experience of investors may not be representative of the experiences of all investors and is not indicative of any future success. The accuracy of information included in the ratings and reviews cannot be guaranteed by Strain Investment Company LLC or any of its affiliates.</p>
    </div>
  </v-card>
</template>