<template>
  <v-card class="m-2">
    <div class="m-4">
      <v-card-title class="text-3xl">Terms and Conditions</v-card-title>
      <p>Your use of our website is governed by the following terms and conditions ("Terms of Use"), as well as the STRAIN INVESTMENT COMPANY LLC Privacy Policy and other operating rules, minimum qualifications and cautions posted throughout the website or presented to you individually during the course of your use of the website (collectively, the "Terms"). The Terms govern your use of the website and STRAIN INVESTMENT COMPANY LLC reserves the right to update or replace the Terms any time without notice.  You are advised to review the Terms for any changes when you visit the website even if you have not received a notification of changes as you are bound by them even if you have not reviewed them.  Your viewing and use of the website after such change constitutes your acceptance of the Terms and any changes to such terms.  If at any time you do not want to be bound by the Terms you should logout, exit and cease using the website immediately.</p>
      <br>

      <v-card-title>Intended Use of Website</v-card-title>
      <p>STRAIN INVESTMENT COMPANY LLC is not a broker-dealer or placement agent.  At no time does STRAIN INVESTMENT COMPANY LLC offer, broker, advise, purchase, sell or otherwise transact in securities regulated by the SEC or federal or state law.  STRAIN INVESTMENT COMPANY LLC does not accept, hold or transfer cash or securities.  STRAIN INVESTMENT COMPANY LLC does not guarantee that a Company seeking investment will achieve any level of success or that any proposed offering will qualify under applicable federal and state securities laws.</p>
      <br>
      <p>STRAIN INVESTMENT COMPANY LLC is not a personal financial advisor.  STRAIN INVESTMENT COMPANY LLC, whether through the website or otherwise, does not provide personal financial advice, loans or credit, banking, consumer credit ratings, credit decisions, financial products, brokerage accounts, insurance, tax advice, legal advice, or financial or legal services of any kind.</p>
      <br>
      <p>STRAIN INVESTMENT COMPANY LLC does not guarantee any results to anyone.  All users of the website are responsible for making their own decisions to use the website and for any activity taken on the website, including without limitation registering and making an investment or otherwise.</p>
      <br>

      <v-card-title>User Registration</v-card-title>
      <p>If you are accepting the Terms on behalf of an organization or entity, rather than in an individual capacity, you represent and warrant that you are authorized to accept the Terms on that organization or entity’s behalf and bind them to these Terms (in which case, the references to "you" and "your" in these Terms, except for in this sentence, refer to that organization or entity).</p>
      <br>
      <p>Only real persons at or above the age of 18 may register for an account and use the website. Registering for an account on the website creates no commitment or obligation on the registered user to make any investment or seek any investment. All information you provide to the website must be truthful, accurate and complete in all material respects. Our registration process may use third-party validation technology, including those provided by third-party social media sites, to attempt to confirm your qualification to use the website.</p>
      <br>
      <p>STRAIN INVESTMENT COMPANY LLC may reject any application to register an individual or an organization or entity for failure to achieve validation through available methods or otherwise meet STRAIN INVESTMENT COMPANY LLC’s registration requirements.</p>
      <br>
      <p>Your registration and the use of any third-party site is subject to the terms and conditions and policies of such sites and STRAIN INVESTMENT COMPANY LLC is not responsible or liable for any harm resulting from the use or misuse of those sites, including when such harm could or does affect your account on this website or use of the website.</p>
      <br>

      <v-card-title>Registered Account Obligations</v-card-title>
      <br>
      <p>The named registered user of an account is the only person that may use the account and it may not be transferred to anyone else.</p>
      <br>
      <p>You are responsible for maintaining the confidentiality of your username and password and to periodically change your password to maintain security.  If you have concerns that your username or password may have been compromised and suspect that unauthorized access to your account or the website has occurred, you must immediately contact STRAIN INVESTMENT COMPANY LLC’s investor support through a secure method (which may not be through your website account).</p>
      <br>

      <v-card-title>Content Use Limitations</v-card-title>
      <p>Your use of the website and its videos, webinars, images, infographics, alerts, text, articles, assessments, checklists, forms, ratings, design, data, source code, analytics, photos, software, trademarks, copyrights, and other information ("Content") may only be used for the lawful and intended purposes expressly authorized by STRAIN INVESTMENT COMPANY LLC. If you access this website from outside the United States, you are solely responsible for ensuring compliance with the laws of your specific jurisdiction, as well as any restrictions that you may be subject to by a department of the United States government. Any misuse or unauthorized use of the website and its Content, or other violations of the Terms may violate Applicable Law (see below), including without limitation SEC regulations and applicable state securities laws, copyright laws (including the Digital Millennium Copyright Act), trademark laws, the laws of privacy, laws of publicity, identity theft and communications statutes and regulations, in which case STRAIN INVESTMENT COMPANY LLC is authorized to terminate your account and access to the website at any time and without notice and report you to the appropriate authorities and other interested parties.</p>
      <br>

      <v-card-title>Prospective Investor Accounts</v-card-title>
      <p>Any person or entity that is considering making an investment with a Company that posts its fundraising plans on the website, or, after the fundraising plan becomes a qualified offering, makes an investment, does so at his or her own risk. All investment carries risk that you may lose some or all of your investment. No Content on the website is a replacement for performing your own due diligence, exercising good judgement, and seeking financial, investment, tax or legal advice from qualified and licensed professionals with knowledge of your personal circumstances. Any registered financial, legal or tax representatives or firm working for or with STRAIN INVESTMENT COMPANY LLC or communicating with you or users in general through the website are not your personal advisors and do not have knowledge about your personal circumstances and anything they post is for informational purposes only and may not be accurate to your situation and you agree that you shall not rely on Content on the website in making personal decisions about an investment or the potential legal, tax or financial consequences of such investment. You are encouraged to seek personal professional advice from qualified and licensed professionals.</p>
      <br>
      <p>You are solely responsible for your investment decisions.  While you may be asked about your identity, individual financial circumstance and investment experience and sophistication during your engagement with the website, STRAIN INVESTMENT COMPANY LLC and its advisors and vendors are not responsible to verify the veracity of the information that you provide, even if you certify to its truth or undergo a suitability review.  Whether you are an "Accredited Investor", as such is defined under securities law, or a non-accredited investor, or an institutional investor, STRAIN INVESTMENT COMPANY LLC and the Companies seeking investment are relying on your representations with respect to your investment experience, your financial status and your eligibility to invest.  You may, further, be held personally liable for your fraud, negligence and other bad acts that may result from any false representations you make.</p>
      <br>

      <v-card-title>Website Fees</v-card-title>
      <p>Should we have to return any investments made through the website for any reason, such as inconsistencies in your legal name, banking information, address, social security number, or date of birth, you may be assessed a nonrefundable, processing fee.  Should your application not make it through the primary verification process, the nonrefundable, processing fee will be retained and the balance of your funds returned.</p>
      <br>

      <v-card-title>Investing Is at Your Own Risk</v-card-title>
      <p>PAST PERFORMANCE IS NO GUARANTEE OF FUTURE RESULTS, AND ANY EXPECTED RETURNS OR HYPOTHETICAL PROJECTIONS MAY NOT REFLECT ACTUAL FUTURE PERFORMANCE. FURTHERMORE, PAST RETURNS MAY REFLECT THE PERFORMANCE OF ASSETS FOR A FINITE TIME, OR DURING A PERIOD OF EXTREME MARKET ACTIVITY.  ALL INVESTMENTS INVOLVE RISK AND MAY RESULT IN PARTIAL OR TOTAL LOSS.  There can be no assurance that an investment mix or any projected or actual performance shown on the website will lead to the expected results shown or perform in any predictable manner.  It should not be assumed that investors will experience returns in the future, if any, comparable to those shown or that any or all investors on the website experienced such returns.</p>
      <br>
      <p>In considering any performance information shown on the website, one should bear in mind that past or targeted performance is not indicative of future results, and there can be no assurance that any issuer will achieve comparable results or that target returns will be met.  One should also bear in mind that targeted portfolio characteristics are not indicative of future results, and there is no assurance that target portfolio characteristic will be achieved.  References to “Targeted IRR” and “Targeted Equity Multiple” represents a property’s internal rate of return (“IRR”) or equity multiple based on such property’s forecasted cash flows generated over a period of time and the amount invested in the property.  This is different from the forecasted IRR or Equity Multiple to the investor in an applicable fund or other investment vehicle.</p>
      <br>
      <p>PROJECTED AND/OR HYPOTHETICAL PERFORMANCE DOES NOT REPRESENT AN ACTUAL INVESTMENT IN ANY OF THE OFFERINGS SPONSORED BY STRAIN INVESTMENT COMPANY LLC, MAY NOT REFLECT THE POTENTIAL EFFECT OF MATERIAL ECONOMIC AND MARKET RELATED FACTORS, AND DO NOT REPRESENT THE ACTUAL PERFORMANCE OR EXPERIENCE OF ANY GIVEN INVESTOR ON ANY STRAIN INVESTMENT COMPANY LLC WEBSITES.  Nothing contained on the website should be deemed to be a prediction for projection of future performance of any issuer.  Prospective investors should make their own investigations and evaluations of the information contained herein.  Each prospective investor should consult its own attorney, business adviser and tax adviser as to legal, business, tax and related matters concerning the information contained herein and such offering.</p>
      <br>
      <p>The information shown on the website uses or includes information compiled from sources outside of STRAIN INVESTMENT COMPANY LLC and its affiliates.  While such information is believed to be reliable for the purposes used herein, neither STRAIN INVESTMENT COMPANY LLC, nor any of its affiliates or partners, members or employees, assume any responsibility for the accuracy of such information.  Unless otherwise indicated, the information on the website has not been reviewed, compiled or audited by any independent third-party or public accountant.  Actual investors on the website may experience different results from any hypothetical results shown.  There is a potential for loss, as well as gain, which is not reflected in the hypothetical information portrayed.  The hypothetical performance results shown do not represent the results of actual investment activity but were achieved by means of the retroactive application of a model designed with the benefit of hindsight.  Investors should carefully review the additional information presented on the website as part of any hypothetical calculation.</p>
      <br>
      <p>Some of the statements contained on the website are forward-looking statements.  You should not rely upon forward-looking statements as predictions of future events.  These statements involve known and unknown risks, uncertainties, and other factors that may cause the project's actual results, levels of activity, performance, or achievements to be materially and adversely different from any future results, levels of activity, performance, or achievements expressed or implied by these forward-looking statements.  An investment in any issuer available on the website involves substantial risks, including risk of partial or total loss of investment, and each investor should carefully consider the Risk Factors contained in each issuer’s offering circular, private placement memorandum, or prospectus.  Except as required by law, neither STRAIN INVESTMENT COMPANY LLC nor any other person assumes responsibility for the accuracy and completeness of the forward-looking statements.  We undertake no obligation to update publicly any forward-looking statements for any reason to conform these statements to actual results or to changes in our expectations.  The information presented regarding each issuer’s offering, including information regarding financial status, business strategy, investment objectives, historical performance, projections, redemption plans, etc., merely constitute a summary of such information and is qualified in its entirety by the disclosure contained in each issuer’s offering circular, private placement memorandum, or prospectus.  There can be no guarantee that any issuer available on the website will achieve its business objectives or that it will become profitable.</p>
      <br>

      <v-card-title>Termination of Account</v-card-title>
      <p>STRAIN INVESTMENT COMPANY LLC may suspend or terminate your account and your ability to use the website at anytime for any lawful reason and STRAIN INVESTMENT COMPANY LLC accepts no liability for any harm that may be caused, directly or indirectly, by such suspension or termination.</p>
      <br>

      <v-card-title>Use of the Website and Content</v-card-title>
      <p>You agree that the Content cannot by copied, reproduced, distributed, republished, displayed, posted, or transmitted in any form or by any means without the express advance written consent of an officer of STRAIN INVESTMENT COMPANY LLC or the applicable licensor.  You may not modify, participate in the sale or transfer of, or create any derivative works based on any part of all of the Content.  Using Content, including by linking, framing, or mirroring for any purpose, is prohibited without the express advance written consent of an officer of STRAIN INVESTMENT COMPANY LLC.</p>
      <br>

      <v-card-title>Availability of Website</v-card-title>
      <p>STRAIN INVESTMENT COMPANY LLC does not warrant the website, its Content or any services provided or offered on the website will be uninterrupted, timely, or virus or error free.  You agree not to modify, damage, disrupt, disable, overburden, impair, alter or interfere with the use, features, functions, operation, security or maintenance of the website or the rights or use and enjoyment of the website by any other person or entity in any manner.  By using the website you release STRAIN INVESTMENT COMPANY LLC, its employees, contractors, advisors, vendors, agents, and affiliates against any and all loss, damage, and claims, in whatever manner, howsoever caused arising from or related to your use of the website.</p>
      <br>

      <v-card-title>Disclaimers, Exclusions, and Limitations of Liability</v-card-title>
      <p>THE WEBSITE AND ITS CONTENT ARE PROVIDED ON AN "AS IS" AND “AS AVAILABLE” BASIS AND USE OF THE WEBSITE IN ANY MANNER IS SOLELY AT YOUR OWN RISK.  TO THE FULLEST EXTENT PERMITTED BY LAW, STRAIN INVESTMENT COMPANY LLC DOES NOT GUARANTEE, AND EXPRESSLY EXCLUDES ALL REPRESENTATIONS AND WARRANTIES, EXPRESS OR IMPLIED, RELATING TO THE WEBSITE AND ITS CONTENT AND PROFESSIONAL SERVICES, WHETHER PROVIDED BY STRAIN INVESTMENT COMPANY LLC, OUR AFFILIATES, OUR CUSTOMERS, COMPANIES SEEKING INVESTMENT, ADVISORS, INVESTORS OR ANY OTHER THIRD PARTY, INCLUDING IN RELATION TO ANY INACCURACIES, ERRORS, OR OMISSIONS ON THE WEBSITE, ITS CONTENT, FINANCIAL ADVICE, AND/OR MARKETING MATERIALS.</p>
      <br>
      <p>STRAIN INVESTMENT COMPANY LLC SHALL HAVE NO LIABILITY FOR DAMAGES ARISING OUT OF OR IN CONNECTION WITH YOUR USE, DELAY, OR UNAVAILABILITY OF THE WEBSITE AND ITS CONTENT, INCLUDING LOSS OF MONEY, INABILITY TO CONCLUDE AN INVESTMENT, SUSPENSION OR TERMINATION OF YOUR ACCOUNT AND FOR ANY DAMAGE CAUSED TO YOUR COMPUTER, COMPUTER SOFTWARE, SYSTEMS, PROGRAMS, AND THE DATA THEREON.  UNDER NO CIRCUMSTANCES WILL STRAIN INVESTMENT COMPANY LLC OR ITS AFFILIATES, ADVISORS AND VENDORS BE LIABLE FOR ANY DAMAGES, INCLUDING GENERAL, SPECIAL, PUNITIVE, DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR ANY OTHER DAMAGES (INCLUDING, WITHOUT LIMITATION, LOST PROFITS OR BUSINESS INTERRUPTION) OF ANY KIND WHETHER IN AN ACTION IN CONTRACT, TORT, OR NEGLIGENCE ARISING OR RELATING IN ANY WAY TO THE USE OR INABILITY TO USE BY ANY PARTY OF THE WEBSITE, THE CONTENT, OR ANY THIRD-PARTY WEBSITE THAT IS LINKED TO BY THE WEBSITE, OR IN CONNECTION WITH ANY FAILURE OF PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DEFECT, DELAY IN OPERATION OR TRANSMISSION, COMPUTER VIRUS, OR LINE OR SYSTEM FAILURE, EVEN IF IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, LOSSES, OR EXPENSES.</p>
      <br>

      <v-card-title>Choice of Law</v-card-title>
      <p>The laws of the State of Florida govern these Terms. Venue for any Dispute arising from your use of the website or otherwise under these Terms and Conditions shall be in Florida.  STRAIN INVESTMENT COMPANY LLC makes no representation that the website is operated in compliance with the laws of any nation but the United States.  If you are located outside the United States, you view this website and access the website at your own risk and initiative.</p>
      <br>
      <p>This website and the Content posted on it or made available through it shall not constitute an offer or solicitation and may not be treated as an offer or solicitation: (i) in any jurisdiction where such an offer or solicitation is against the law; (ii) to anyone to whom it is unlawful to make such an offer or solicitation; or (iii) if the person making the offer or solicitation is not qualified to do so.  Any securities that may be offered on the website can only be marketed in certain jurisdictions.  You acknowledge and agree that it is solely your responsibility to be aware of the applicable laws and regulations of your country and U.S. state of residence.</p>
      <br>

      <v-card-title>Waiver</v-card-title>
      <p>Failure of STRAIN INVESTMENT COMPANY LLC to insist upon strict performance of any provision of the Terms or the failure of STRAIN INVESTMENT COMPANY LLC to exercise any right or remedy to which it is entitled shall not constitute a waiver thereof and shall not affect the validity of the Terms, or any part, or STRAIN INVESTMENT COMPANY LLC's right to enforce each and every provision.  If any of the Terms are deemed invalid or unenforceable for any reason (including, but not limited to the exclusions and limitations set out above), then the invalid or unenforceable provision will be severed from the Terms and the remaining Terms will continue to apply.</p>
      <br>

      <v-card-title>Electronic Funds Transfers</v-card-title>
      <p>STRAIN INVESTMENT COMPANY LLC processes Electronic Funds Transfers (EFTs) as an efficient method to receive electronic deposits from investors, to purchase and redeem investments and to issue refunds to investors. EFTs are processed through the vehicles described below:</p>
      <p>    ● The Automated Clearing House (ACH)</p>
      <p>    ● The Fedwire</p>
      <p>    ● Credit Card</p>
      <br>

      <v-card-title>Electronic Funds Transfers Agreement and Disclosure</v-card-title>
      <p>This Electronic Funds Transfers Agreement and Disclosure (this Agreement) is the contract which covers you and our rights and responsibilities concerning the EFTs services offered to you by STRAIN INVESTMENT COMPANY LLC.  In this Agreement, the words “you,” “your,” and “yours” mean an individual who signs up on the STRAIN INVESTMENT COMPANY LLC Online Platform (Platform) and utilizes the Platform to participate in offerings (and any authorized users).  The words “we,” “us,” and “our” mean STRAIN INVESTMENT COMPANY LLC.  EFTs are electronically initiated transfers of money from your bank account or credit card account, which you utilize the Platform to initiate, and which allow you to participate in the STRAIN INVESTMENT COMPANY LLC offerings.  By using any STRAIN INVESTMENT COMPANY LLC service, you agree to the terms and conditions in this Agreement and any amendments for the EFTs services offered.</p>
      <br>
      <p>In order to use the payment functionality of STRAIN INVESTMENT COMPANY LLC, you authorize us to share your identity, bank account data and credit card account data with North Capital Private Securities (NCPS), a broker-dealer registered with the Securities and Exchange Commission and the Financial Industry Regulatory Authority, Inc., and with North Capital Investment Technology (NCIT) for the purpose of processing your EFTs, and you are responsible for the accuracy and completeness of that data.  You understand that you will access and are responsible for managing your bank account data and credit card account data through the Platform.  You also authorize us and NCPS and NCIT to process EFTs as you direct through STRAIN INVESTMENT COMPANY LLC.</p>
      <br>
      <p>You acknowledge that none of NCPS, NCIT or we will be liable for any loss, expense or cost arising out of EFT services provided through your use of STRAIN INVESTMENT COMPANY LLC, which are based on your instruction; NCPS and NCIT are third party beneficiaries to this Agreement.</p>
    </div>
  </v-card>
</template>